### ISSUE TITLE
CamYou

### ISSUE THREAD

**Issue by VackerSimon** [ZombieAlex/MFCAuto#15]
Have you considered adding support for CamYou? Since the differences between MFC and CamYou are very few (on the technical side).

I managed to connect to CamYou by replacing the URLs, adding "2/" before the username and password that is sent with Client.login, and changing toRoomId and toUserId to -400000000. I do seem to get disconnected after a short time tho.

**Comment by ZombieAlex** [comment]
I've thought about it. It shouldn't be too hard to do. As you say, their sources are largely shared. But given that CamYou is empty most of the time still, it's been way down my priority list.

I'll keep this open and track it for a future release. Knowing people are interested definitely motivates me, so I wouldn't be surprised if I get to it in the next week or two.

Since you've already done some sleuthing on it, if you don't want to wait for me I'm open to a pull request. Right now I think I'd add another optional parameter to the Client constructor controlling which site to use and otherwise leave the MFCAuto API unchanged.

**Comment by VackerSimon** [comment]
While I've gotten it to work somewhat, it still disconnects after about 20 seconds or so. Haven't figured out why yet.

**Comment by VackerSimon** [comment]
Fixed the disconnects. There's so little traffic that the keepAlive functions assumes the connection has been lost, set the if-statement to "this.trafficCounter > 0" and made it reset the counter before sending the NULL packet. I don't know if the response for sending the NULL packet is enough to know the connection is good but it's at least working for now.

**Comment by ZombieAlex** [comment]
Ahh, that makes sense. 

> I don't know if the response for sending the NULL packet is enough to know the connection is good

Unfortunately it's not enough. I added that trafficCounter check specifically because I had seen Clients fall into a zombie state where they were connected and getting ping responses, but no model session state information was flowing through despite thousands of models being online. I suspect they may have been intentionally doing that on the server side to throttle bots and other MFCAuto-like automation.

Would have to think a bit about a more complete solution to that problem.

**Comment by ZombieAlex** [comment]
Just published v4.2.0 with basic CamYou support. I didn't make any changes to the trafficCount logic, but I did make an unrelated change that should increase the number of messages sent from the server. As long as CamYou isn't completely deserted, it should make disconnects less common.

Leaving this issue open for a bit as I haven't extensively tested CamYou. If you have problems or continued disconnects, please add them here.

One nice thing I found about CamYou is that because the traffic is so low, it's a little easier to read and understand the packet flow to and from the server. So that's cool.

Thanks.

**Comment by VackerSimon** [comment]
Thanks! I'll test it in the coming days

**Comment by ZombieAlex** [comment]
Two weeks ago, in v4.2.2, I added tests for all the core MFCAuto functionality when using CamYou, and everything seems to work. But I still haven't run any long-running tests to check the traffic timeout conditions.

I'm going to go ahead and close this issue since the core support is there now. If you find bugs with it, go ahead and log new issues. Thanks.

**Comment by ZombieAlex** [comment]
By the way, I haven't documented it well but in v5.0.0 I changed the trafficCount/timeout logic and made it configurable via the same Client options bag that enables camYou support. The relevant new options are:

```javascript
const mfc = require("MFCAuto");
let client = new mfc.Client("guest", "guest", {
    camYou: true
    /** 
     * Assume disconnected if we've received nothing
     * from the server after this many milliseconds.
     * Default 90 seconds
     */
    silenceTimeout: 90000,
    /**
     * Assume disconnected if we've received no packets
     * which would update a model status after this many
     * milliseconds. Default 2 minutes
     */
    stateSilenceTimeout: 120000,
});
```

The default of the latter especially might trip on CamYou sometimes when there are no models online. But you can customize the timeouts now or even explicitly set them to `undefined` in your options to enable infinite timeouts (though I wouldn't advise that).
