### ISSUE TITLE
findModels returning increasing list of online models

### ISSUE THREAD

**Issue by jrudess** [ZombieAlex/MFCAuto#6]
When I run the findModels() routine in order to grab a list of all online models, I'm seeing that the return array  continues to grow in size over time.  I called the following findModels() query every 5 minutes for 12 hours and the return size grew to over 8000 entries.

var onlineModels = mfc.Model.findModels((m) => m.bestSession.vs !== mfc.STATE.Offline);

I started dumping the return value to a file on each call and diffing the files.  I can see that models are both being added and deleted from the list, and have not yet tracked down a pattern.  My best guess is that models are going offline, and this is not being caught and their bestSession.vs still reports them in one of the online states.

I'm currently debugging this and wanted to submit this issue in case you have any insights that might aid the debug process.

**Comment by ZombieAlex** [comment]
Thanks for the report.

I'm assuming you're running this in a loop with one continuously connected client.  Is that correct?  In practice, when monitoring specific models in a long running (several weeks) process, I've found the tracking to be accurate for them.  But I can't say I've tried validating _every_ model status like in your case.

Couple questions:

- Are you logged in as a guest or a real account?
- Are you joining any chat rooms?
- Do you see the same 'leak' with other filters like m.bestSession.vs === mfc.STATE.FreeChat?  I can run my own tests but I'm wondering if the issue is specific to the offline state or not.

Possible issues:

- MFC sends model state updates as part of many different packet types. In MFCAuto, this is handled in Client._packetReceived where I check the packet type and if it's known to possibly contain a state update, I call mergePacket on the matching model instance.  That updates the model's state.  It is possible that I'm missing a packet type there.  Although double checking MFC's site code just now, I don't see an obvious mismatch between what they're doing and what MFCAuto is doing.  Their equivalent code is in top.html in their ProcessPacket function. There they call StoreUserHash on any packet that contains a model state update.
- One known caveat is that MFC pulls state from FCTYPE.BOOKMARK packets and MFCAuto does not.  So if you're logged in with an account that has bookmarked some models.  That could be the issue.

Here's what I'd suggest to debug:

1. Log all received packets to a file (similar to the last example in the README but save it to a file)
2. Run your code until you're certain you've experienced the issue
3. Identify one model with certainly incorrect status
4. Search for all references to her model ID in your full packet log

If the final model status seems to have the correct value in the log but not in .findModels, then we failed to merge an update somewhere.  At that point I should be able to fix it if you share the log, the model's ID, and her expected correct status.

**Comment by jrudess** [comment]
Thanks for the great info.   I am logging in as a guest and leaving that session open.  I'm not joining any chat rooms.

There's actually not a specific need for me to query for all online models since MFCAuto lets me query status of models individually.  However, I'm integrating MFCAuto into an existing codebase  that supports multiple sites, so for initial integration it was faster to integrate it by returning the full online model list that the code base currently expects.   At some point I will probably rip this part out anyway and query vs only for specific models

I'm working on your debug suggestions, and if I can isolate a specific model getting out of sync, I will provide the logs.

**Comment by ZombieAlex** [comment]
At the moment I've had the test code below running for 24 hours straight.  It is currently reporting 1672 models matching this filter:

```javascript
mfc.Model.findModels((m) => m.bestSession.vs !== mfc.STATE.Offline)
```

And 1273 models matching this filter:

```javascript
mfc.Model.findModels((m) => m.bestSession.vs !== mfc.STATE.Offline && m.bestSession.vs !== mfc.STATE.Online)
```

Neither number has climbed drastically.  Note that this second filter corresponds to what MFC displays on their main page when they say "X Models Online".  They don't include models in mfc.STATE.Online, meaning logged in but not on cam or "away".

My full test code:
```javascript
let mfc = require("MFCAuto");
let log = mfc.log;

let client = new mfc.Client();

client.on("ANY", (packet) => {
    log(packet.toString(), "packetLog", null);
});

function verifyModels() {
    let onlineModels = mfc.Model.findModels((m) => m.bestSession.vs !== mfc.STATE.Offline);
    let notOnlineOfflineModels = mfc.Model.findModels((m) => m.bestSession.vs !== mfc.STATE.Offline && m.bestSession.vs !== mfc.STATE.Online);
    log(`Found ${onlineModels.length} models online and ${notOnlineOfflineModels.length} models not offline/online`);
    for (let i = 0; i < onlineModels.length; i += 200) {
        let preQueryStatus = onlineModels[i].bestSession.vs;
        client.queryUser(onlineModels[i].uid)
            .then((m) => {
                if (m.bestSession.vs !== preQueryStatus) {
                    log(`Model: ${m.uid}, Previously known state: ${preQueryStatus}, Correct state: ${m.bestSession.vs}`, "packetLog");
                    process.exit();
                }
            });
    }
}

client.connectAndWaitForModels().then(() => {
    setInterval(() => verifyModels(), 60 * 1000);
});
```

The code is also spot checking a few model's status every 60 seconds by explicitly querying MFC via client.queryUser and it has found no inconsistencies.

Are you doing something fundamentally different than this in your script?  Can you still repro?  If so, can you share your code?

**Comment by jrudess** [comment]
Work got me busy and I haven't had a chance to dig into the debug deeper yet. I just checked a process that has been running for ~24 hours and it is currently returning 1754 online models with
`m.bestSession.vs !== mfc.STATE.Offline`
 
This looks like a reasonable value, especially since I did not realize that the frontpage count on MFC did not include 'away' or 'cam off' models.  Over this last weekend, I saw one case where the return array size grew to over 10000, but have not seen it grow that fast or high since.

In my repo, I perform the query in mfc.js in the getOnlineModels() function.  The returned array size is printed out in main.js in the mainSiteLoop() function.

**Comment by jrudess** [comment]
BTW, for this comment in sMessages.ts

` camserv?: number;       // Details about which MFC video server is hosting the users's video stream.  Haven't fully deciphered this @TODO`

The details of what the value means can be found in mfc.js in the setupCapture() routine

**Comment by jrudess** [comment]
Closing this old issue out -- haven't had time to dig deeper and prove it's not an issue in my own code.
