### ISSUE TITLE
this is not work more

### ISSUE THREAD

**Issue by marabu88** [ZombieAlex/MFCAuto#8]
hi! myfreecams change something. you know how fix it?

**Comment by jrudess** [comment]
Many things still seem to work fine, but specifically connectAndWaitForModels() will hang as CLIENT_MODELSLOADED is never emitted.

**Comment by ZombieAlex** [comment]
Thanks for the report, and @jrudess thanks a ton for those details. I've been swamped with my day job and hadn't seen this issue until now.  Will take a look.

**Comment by ZombieAlex** [comment]
Yep, at a glance it looks like that stopped sending an FCTYPE.METRICS packet when the model list starts and finishes loading, and instead they send an FCTYPE.EXTDATA packet at the start with the count of online models (as sMessage.msg.arg1).

The fix is probably going to be to have Client consume that initial EXTDATA packet, pull out the model count, and then wait until it gets SESSIONSTATE packets for that many models before emitting CLIENT_MODELSLOADED.  Probably.

I need to test out some scenarios (and eat dinner) but I should be able to fix this and publish an update sometime in the next few hours.

**Comment by ZombieAlex** [comment]
Good news is that I understand what's happening now.  Bad news is that it's more complicated than I originally thought and has implications beyond just connectAndWaitForModels().

The short version is that they've moved a lot of the initial server communication out of the chat server protocol and into a redis cache, which greatly speeds up initial page load on their site, but leaves the current MFCAuto with an incomplete view of the world.

It's fixable but this will be a larger change.  Stay tuned.

**Comment by ZombieAlex** [comment]
I've published v3.4.1 which should fix most scenarios, but this was a major change in the way their servers communicate status.  There are likely additional bugs in v3.4.1.  Please file a new issue if you hit any.

And thanks again for the report.
